Turned out UseAntiforgery is necessary after all
When running the app in release mode it throws this exception:

System.InvalidOperationException: Endpoint /login (/login) contains
anti-forgery metadata, but a middleware was not found that supports
anti-forgery.
Configure your application startup by adding app.UseAntiforgery() in the
application startup code. If there are calls to app.UseRouting() and
app.UseEndpoints(...), the call to app.UseAntiforgery() must go between
them. Calls to app.UseAntiforgery() must be placed after calls to
app.UseAuthentication() and app.UseAuthorization().